spring.application.name=demo
logging.level.root=INFO
logging.level.com.example.loggingdemo=DEBUG
user.controller.port=8081
user.controller.host-name=localhost
spring.profiles.active=dev
user.min-age=0